language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install .
# command to run tests, e.g. python setup.py test
script:  py.test -rf -l -s -x --cov-report term-missing --cov val.py
