#!/bin/sh
# to enable this in your checkout (which I suggest is a good idea), run:
# ln pre-commit .git/hooks/pre-commit
# (You will need to install tox for this to work)
git stash -q --keep-index
tox
RESULT=$?
git stash pop -q
[ $RESULT -ne 0 ] && exit 1
exit 0
